eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  server:
    enable-self-preservation: true