server:
  port: 8088
  servlet:
    context-path: /mq

spring:
  application:
    name: mq
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: mq
    password: mq123
    virtual-host: /
    #publisher-confirm-type: correlated # 成功给或失败信息返回。事务模式别打开
    #publisher-returns: true # 不可路由信息，路由key不存在是否处理。事务模式别打开
    #listener:
     # simple:
      #  acknowledge-mode: manual # 手动确认

default:
  prefetch:
    count: 10
  concurrent: 5