server:
  session-timeout: 7200
  port: 8087

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 激活的配置文件
  profiles:
    active: es

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
