server:
  session-timeout: 7200
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8080
#    uri-encoding: utf-8
spring:
  application:
    name: admin
  thymeleaf:
    mode: HTML
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 激活的配置文件
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
